source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Utility_Example', :exclusive => true do
  pod 'Utility', :path => '../'
end

target 'Utility_Tests', :exclusive => true do
  pod 'Utility', :path => '../'

  
end
